scissors_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: scissors_finger
    joint_speed: 1.0
    motor:
        id: 1
        init: 2048
        min: 0
        max: 4095

scissors_trajectory_controller:
    controller:
        package: dynamixel_controllers
        module: joint_trajectory_action_controller
        type: JointTrajectoryActionController
    joint_trajectory_action_node:
        min_velocity: 0.1
        constraints:
            goal_time: 0.25
